export const inventorsLeads = [
	{
		id: 1,
		name: 'Happiness Omale',
		position: 'Social Media Manager',
		school: 'OAUSTECH',
		email: 'omalehappiness@gmail.com',
		phone: '+234 706 765 2134',
		status: 'Approved',
		alumni: true,
	},
	{
		id: 2,
		name: 'Owosupi Kehinde',
		position: 'Software Engineer',
		school: 'OAUSTECH',
		email: 'owosupikehinde@gmail.com',
		phone: '+234 706 765 2134',
		status: 'Approved',
		alumni: true,
	},
	{
		id: 3,
		name: 'Adesokan Oluwajuwon',
		position: 'Co-Founder',
		school: 'OAUSTECH',
		email: 'adesokanoluwa@gmail.com',
		phone: '+234 706 765 2134',
		status: 'Declined',
		alumni: true,
	},
	{
		id: 4,
		name: 'Kelvin Doe',
		school: 'Bells University',
		email: 'kelvin@gmail.com',
		phone: '+234 706 765 2134',
		status: 'Deactivated',
		alumni: false,
	},
	{
		id: 5,
		name: 'Owosupi Kehinde',
		school: 'OAUSTECH',
		email: 'owosupikehinde@gmail.com',
		phone: '+234 706 765 2134',
		status: 'Approved',
		alumni: true,
	},
	{
		id: 6,
		name: 'Kelvin Doe',
		school: 'Bells University',
		email: 'kelvin@gmail.com',
		phone: '+234 706 765 2134',
		status: 'Unapproved',
		alumni: false,
	},
	{
		id: 7,
		name: 'Kelvin Doe',
		school: 'Bells University',
		email: 'kelvin@gmail.com',
		phone: '+234 706 765 2134',
		status: 'Approved',
		alumni: false,
	},
];
