export const inventorsLeads = [
  {
    id: 1,
    name: "Happiness Omale",
    position: "Social Media Manager",
    school: "OAUSTECH",
    email: "omalehappiness@gmail.com",
    phone: "+234 706 765 2134",
    status: "Approved",
    alumni: true,
    location: "Lagos, Nigeria",
    interests: "Digital Marketing, Content Creation",
    experience: "5 years in social media management",
    primarySkill: "Social Media Strategy",
    secondarySkill: "Content Marketing",
    bio: "A passionate social media manager with a knack for creating engaging content.",
    technologies: ["Hootsuite", "Canva", "Google Analytics"],
    skillProfileURL: "https://www.linkedin.com/in/happiness-omale",
    personalWebsite: "http://happinessomale.com",
    twitter: "https://twitter.com/happinessomale",
    linkedin: "https://www.linkedin.com/in/happinessomale",
    facebook: "https://www.facebook.com/happinessomale",
  },
  {
    id: 2,
    name: "Owosupi Kehinde",
    position: "Software Engineer",
    school: "OAUSTECH",
    email: "owosupikehinde@gmail.com",
    phone: "+234 706 765 2134",
    status: "Approved",
    alumni: true,
    location: "Ibadan, Nigeria",
    interests: "Web Development, AI",
    experience: "3 years in software development",
    primarySkill: "JavaScript",
    secondarySkill: "React",
    bio: "A dedicated software engineer with a focus on building scalable web applications.",
    technologies: ["JavaScript", "React", "Node.js"],
    skillProfileURL: "https://www.linkedin.com/in/owosupikehinde",
    personalWebsite: "http://owosupikehinde.com",
    twitter: "https://twitter.com/owosupikehinde",
    linkedin: "https://www.linkedin.com/in/owosupikehinde",
    facebook: "https://www.facebook.com/owosupikehinde",
  },
  {
    id: 3,
    name: "Adesokan Oluwajuwon",
    position: "Co-Founder",
    school: "OAUSTECH",
    email: "adesokanoluwa@gmail.com",
    phone: "+234 706 765 2134",
    status: "Declined",
    alumni: true,
    location: "Abuja, Nigeria",
    interests: "Entrepreneurship, Technology",
    experience: "2 years as a startup co-founder",
    primarySkill: "Business Development",
    secondarySkill: "Strategic Planning",
    bio: "An aspiring entrepreneur with a passion for technology and innovation.",
    technologies: ["Startup Methodologies", "Agile", "Market Research"],
    skillProfileURL: "https://www.linkedin.com/in/adesokanoluwa",
    personalWebsite: "http://adesokanoluwa.com",
    twitter: "https://twitter.com/adesokanoluwa",
    linkedin: "https://www.linkedin.com/in/adesokanoluwa",
    facebook: "https://www.facebook.com/adesokanoluwa",
  },
  {
    id: 4,
    name: "Kelvin Doe",
    position: "Project Manager",
    school: "Bells University",
    email: "kelvin@gmail.com",
    phone: "+234 706 765 2134",
    status: "Deactivated",
    alumni: false,
    location: "Port Harcourt, Nigeria",
    interests: "Project Management, Leadership",
    experience: "4 years in project management",
    primarySkill: "Agile Methodologies",
    secondarySkill: "Team Leadership",
    bio: "An experienced project manager skilled in leading teams and delivering projects on time.",
    technologies: ["Trello", "JIRA", "Microsoft Project"],
    skillProfileURL: "https://www.linkedin.com/in/kelvindoe",
    personalWebsite: "http://kelvindoe.com",
    twitter: "https://twitter.com/kelvindoe",
    linkedin: "https://www.linkedin.com/in/kelvindoe",
    facebook: "https://www.facebook.com/kelvindoe",
  },
  {
    id: 5,
    name: "Owosupi Kehinde",
    position: "Software Engineer",
    school: "OAUSTECH",
    email: "owosupikehinde@gmail.com",
    phone: "+234 706 765 2134",
    status: "Approved",
    alumni: true,
    location: "Ibadan, Nigeria",
    interests: "Web Development, AI",
    experience: "3 years in software development",
    primarySkill: "JavaScript",
    secondarySkill: "React",
    bio: "A dedicated software engineer with a focus on building scalable web applications.",
    technologies: ["JavaScript", "React", "Node.js"],
    skillProfileURL: "https://www.linkedin.com/in/owosupikehinde",
    personalWebsite: "http://owosupikehinde.com",
    twitter: "https://twitter.com/owosupikehinde",
    linkedin: "https://www.linkedin.com/in/owosupikehinde",
    facebook: "https://www.facebook.com/owosupikehinde",
  },
  {
    id: 6,
    name: "Kelvin Doe",
    position: "Quality Assurance Engineer",
    school: "Bells University",
    email: "kelvin@gmail.com",
    phone: "+234 706 765 2134",
    status: "Unapproved",
    alumni: false,
    location: "Enugu, Nigeria",
    interests: "Software Testing, Automation",
    experience: "2 years in QA",
    primarySkill: "Automated Testing",
    secondarySkill: "Performance Testing",
    bio: "A detail-oriented QA engineer with a passion for ensuring software quality.",
    technologies: ["Selenium", "JMeter", "Postman"],
    skillProfileURL: "https://www.linkedin.com/in/kelvindoe",
    personalWebsite: "http://kelvindoe.com",
    twitter: "https://twitter.com/kelvindoe",
    linkedin: "https://www.linkedin.com/in/kelvindoe",
    facebook: "https://www.facebook.com/kelvindoe",
  },
  {
    id: 7,
    name: "Kelvin Doe",
    position: "Systems Analyst",
    school: "Bells University",
    email: "kelvin@gmail.com",
    phone: "+234 706 765 2134",
    status: "Approved",
    alumni: false,
    location: "Owerri, Nigeria",
    interests: "Systems Design, Data Analysis",
    experience: "3 years as a systems analyst",
    primarySkill: "Data Analysis",
    secondarySkill: "Systems Integration",
    bio: "A systems analyst with expertise in analyzing and improving IT systems.",
    technologies: ["SQL", "Python", "Tableau"],
    skillProfileURL: "https://www.linkedin.com/in/kelvindoe",
    personalWebsite: "http://kelvindoe.com",
    twitter: "https://twitter.com/kelvindoe",
    linkedin: "https://www.linkedin.com/in/kelvindoe",
    facebook: "https://www.facebook.com/kelvindoe",
  },
  // New entry for Temoye Dennis
  {
    id: 8,
    name: "Temoye Dennis",
    position: "Frontend Developer",
    school: "OAUSTECH",
    email: "temoyedennis@gmail.com",
    phone: "+234 706 765 2134",
    status: "Approved",
    alumni: true,
    location: "Lagos, Nigeria",
    interests: "Frontend Development, User Experience",
    experience: "5 years in frontend development",
    primarySkill: "React",
    secondarySkill: "Next.js",
    bio: "A frontend developer and computer engineer with a passion for creating responsive and user-friendly web applications.",
    technologies: [
      "React",
      "Next.js",
      "Chakra UI",
      "Tailwind CSS",
      "Redux",
      "React Native",
      "PHP",
    ],
    skillProfileURL: "https://www.linkedin.com/in/temoyedennis",
    personalWebsite: "http://temoyedennis.com",
    twitter: "https://twitter.com/temoyedennis",
    linkedin: "https://www.linkedin.com/in/temoyedennis",
    facebook: "https://www.facebook.com/temoyedennis",
  },
];
