export const inventorsLeads = [
	{
	  id: 1,
	  name: 'Happiness Omale',
	  position: 'Social Media Manager',
	  company: 'MediaSpark',
	  school: 'OAUSTECH',
	  email: 'omalehappiness@gmail.com',
	  phone: '+234 706 765 2134',
	  location: 'Akure, Nigeria',
	  experience: '3 Years',
	  primarySkill: 'Content Strategy',
	  secondarySkill: 'Analytics',
	  interests: ['Marketing', 'Branding'],
	  tools: ['Canva', 'Buffer', 'Google Analytics'],
	  bio: 'Experienced social media manager skilled in growing brand presence across platforms and analyzing performance metrics.',
	  links: {
		profile: 'https://mediaspark.io/omale',
		portfolio: 'https://omaleportfolio.com',
		twitter: 'https://twitter.com/omalehappiness',
		linkedin: 'https://linkedin.com/in/omalehappiness',
		facebook: 'https://facebook.com/omalehappiness',
	  },
	  status: 'Approved',
	  alumni: true,
	},
	{
	  id: 2,
	  name: 'Owosupi Kehinde',
	  position: 'Software Engineer',
	  company: 'TechNest Inc.',
	  school: 'OAUSTECH',
	  email: 'owosupikehinde@gmail.com',
	  phone: '+234 706 765 2134',
	  location: 'Ibadan, Nigeria',
	  experience: '4 Years',
	  primarySkill: 'Fullstack Development',
	  secondarySkill: 'DevOps',
	  interests: ['Web Development', 'Cloud Infrastructure'],
	  tools: ['Node.js', 'React', 'Docker', 'MongoDB'],
	  bio: 'Dedicated software engineer with a passion for building scalable applications and seamless user experiences.',
	  links: {
		profile: 'https://technest.io/kkehinde',
		portfolio: 'https://kehinde.dev',
		twitter: 'https://twitter.com/kkehinde',
		linkedin: 'https://linkedin.com/in/kkehinde',
		facebook: 'https://facebook.com/kkehinde',
	  },
	  status: 'Approved',
	  alumni: true,
	},
	{
	  id: 3,
	  name: 'Adesokan Oluwajuwon',
	  position: 'Co-Founder',
	  company: 'StartBox',
	  school: 'OAUSTECH',
	  email: 'adesokanoluwa@gmail.com',
	  phone: '+234 706 765 2134',
	  location: 'Lagos, Nigeria',
	  experience: '5 Years',
	  primarySkill: 'Product Management',
	  secondarySkill: 'Business Development',
	  interests: ['Startups', 'Product Design'],
	  tools: ['Figma', 'Jira', 'Slack'],
	  bio: 'Entrepreneur and product enthusiast focused on launching tech solutions that solve real-world problems.',
	  links: {
		profile: 'https://startbox.com/oluwa',
		portfolio: 'https://oluwajuwon.dev',
		twitter: 'https://twitter.com/oluwa_j',
		linkedin: 'https://linkedin.com/in/adesokan',
		facebook: 'https://facebook.com/adesokanoluwa',
	  },
	  status: 'Declined',
	  alumni: true,
	},
	{
	  id: 4,
	  name: 'Kelvin Doe',
	  position: 'Software Engineer',
	  company: 'Microsoft',
	  school: 'Bells University',
	  email: 'kelvindoe@gmail.com',
	  phone: '+234 802 845 8888',
	  location: 'Lagos, Nigeria',
	  experience: '2 Years',
	  primarySkill: 'Software Engineer',
	  secondarySkill: 'Data Analyst',
	  interests: ['UI design', 'Product design'],
	  tools: ['React JS', 'Micro', 'Click Up', 'Java', 'C++', 'HTML', 'CSS', 'Vue JS'],
	  bio: "I'm a self taught developer with 6 years experience building amazing digital products that solves users problems.",
	  links: {
		profile: 'https://thisisaurl.com',
		portfolio: 'https://thisisaurl.com',
		twitter: 'https://thisisaurl.com',
		linkedin: 'https://thisisaurl.com',
		facebook: 'https://thisisaurl.com',
	  },
	  status: 'Deactivated',
	  alumni: false,
	},
	{
	  id: 5,
	  name: 'Owosupi Kehinde',
	  position: 'Software Engineer',
	  company: 'TechNest Inc.',
	  school: 'OAUSTECH',
	  email: 'owosupikehinde@gmail.com',
	  phone: '+234 706 765 2134',
	  location: 'Ibadan, Nigeria',
	  experience: '4 Years',
	  primarySkill: 'Fullstack Development',
	  secondarySkill: 'DevOps',
	  interests: ['Web Development', 'Cloud Infrastructure'],
	  tools: ['Node.js', 'React', 'Docker', 'MongoDB'],
	  bio: 'Dedicated software engineer with a passion for building scalable applications and seamless user experiences.',
	  links: {
		profile: 'https://technest.io/kkehinde',
		portfolio: 'https://kehinde.dev',
		twitter: 'https://twitter.com/kkehinde',
		linkedin: 'https://linkedin.com/in/kkehinde',
		facebook: 'https://facebook.com/kkehinde',
	  },
	  status: 'Approved',
	  alumni: true,
	},
	{
	  id: 6,
	  name: 'Kelvin Doe',
	  position: 'Software Engineer',
	  company: 'Microsoft',
	  school: 'Bells University',
	  email: 'kelvindoe@gmail.com',
	  phone: '+234 802 845 8888',
	  location: 'Lagos, Nigeria',
	  experience: '2 Years',
	  primarySkill: 'Software Engineer',
	  secondarySkill: 'Data Analyst',
	  interests: ['UI design', 'Product design'],
	  tools: ['React JS', 'Micro', 'Click Up', 'Java', 'C++', 'HTML', 'CSS', 'Vue JS'],
	  bio: "I'm a self taught developer with 6 years experience building amazing digital products that solves users problems.",
	  links: {
		profile: 'https://thisisaurl.com',
		portfolio: 'https://thisisaurl.com',
		twitter: 'https://thisisaurl.com',
		linkedin: 'https://thisisaurl.com',
		facebook: 'https://thisisaurl.com',
	  },
	  status: 'Unapproved',
	  alumni: false,
	},
	{
	  id: 7,
	  name: 'Kelvin Doe',
	  position: 'Software Engineer',
	  company: 'Microsoft',
	  school: 'Bells University',
	  email: 'kelvindoe@gmail.com',
	  phone: '+234 802 845 8888',
	  location: 'Lagos, Nigeria',
	  experience: '2 Years',
	  primarySkill: 'Software Engineer',
	  secondarySkill: 'Data Analyst',
	  interests: ['UI design', 'Product design'],
	  tools: ['React JS', 'Micro', 'Click Up', 'Java', 'C++', 'HTML', 'CSS', 'Vue JS'],
	  bio: "I'm a self taught developer with 6 years experience building amazing digital products that solves users problems.",
	  links: {
		profile: 'https://thisisaurl.com',
		portfolio: 'https://thisisaurl.com',
		twitter: 'https://thisisaurl.com',
		linkedin: 'https://thisisaurl.com',
		facebook: 'https://thisisaurl.com',
	  },
	  status: 'Approved',
	  alumni: false,
	},
  ];
  